### ISSUE TITLE
关于Latex Calculator的请教

### ISSUE THREAD

**Issue by xiaoxiaoli666** [NASA-NJU/UNISON-for-ns-3#6]
hello，在F5笔记本中看到大佬的latex calculator，在github上没有看到项目，没法在下边提issue了，就把问题加在这里了，想和大佬请教下latex Calculator的计算逻辑是什么样的？是用python的sympy库做的吗还是math库呀？诚盼大佬回复~

**Comment by F5Soft** [comment]
就是做了个类似编译器的东西，把 LaTeX 语法转换成 sympy 语法，然后调用 sympy 求解。因为之前是给一个商业项目写的，所以目前没有开源）
